/// Flutter icons MyPortFicon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyPortFicon
///      fonts:
///       - asset: fonts/MyPortFicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyPortFicon {
  MyPortFicon._();

  static const _kFontFam = 'MyPortFicon';
  static const String? _kFontPkg = null;

  static const IconData api_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imageicon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
